FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apt-get update

COPY requirements.txt .
RUN pip install -U pip setuptools wheel \
    && pip install -r requirements.txt

COPY . .

CMD ["sh", "./resources/scripts/entrypoint.sh"]
