"""Income and expense type added

Revision ID: 0325b3b34d1d
Revises: d411fbb230d9
Create Date: 2025-02-07 14:50:17.806417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0325b3b34d1d'
down_revision: Union[str, None] = 'd411fbb230d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
