"""test running migrations

Revision ID: 09d77f77c3b6
Revises: 5ffeec9b6f06
Create Date: 2025-02-17 17:14:34.992055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d77f77c3b6'
down_revision: Union[str, None] = '5ffeec9b6f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
