"""test running migrations

Revision ID: 12b46c1aeb65
Revises: d2fb6cbbd98c
Create Date: 2025-02-20 17:00:17.201332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b46c1aeb65'
down_revision: Union[str, None] = 'd2fb6cbbd98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
