"""just basic migrations

Revision ID: 2ae96e40848f
Revises: 2da23b5ca597
Create Date: 2025-02-03 19:38:32.774420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ae96e40848f'
down_revision: Union[str, None] = '2da23b5ca597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expected_value', sa.Column('price', sa.BigInteger(), nullable=False))
    op.alter_column('expected_value', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expected_value', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('expected_value', 'price')
    # ### end Alembic commands ###
