"""adding lasting models login and password

Revision ID: 2af9a43b7aed
Revises: 86b1549593f7
Create Date: 2025-02-07 12:23:17.420701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af9a43b7aed'
down_revision: Union[str, None] = '86b1549593f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE expensefromwhom AS ENUM ('oybek', 'bahrom', 'income');")
    op.add_column('expences', sa.Column('from_whom', sa.Enum('oybek', 'bahrom', 'income', name='expensefromwhom'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expences', 'from_whom')
    # ### end Alembic commands ###
