"""test running migrations

Revision ID: 39a8498ef7e5
Revises: 6edf1390c316
Create Date: 2025-02-17 20:24:32.440077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a8498ef7e5'
down_revision: Union[str, None] = '6edf1390c316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
