"""test running migrations

Revision ID: 40b3bb181f6a
Revises: f98bd0fa39d7
Create Date: 2025-02-17 18:04:50.966827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b3bb181f6a'
down_revision: Union[str, None] = 'f98bd0fa39d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
