"""test running migrations

Revision ID: 62dd4b2cae06
Revises: 0a2c1ab39258
Create Date: 2025-02-18 21:44:22.661114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dd4b2cae06'
down_revision: Union[str, None] = '0a2c1ab39258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
