"""test running migrations

Revision ID: 682e6b0f0f9e
Revises: 6b2d7be8deb7
Create Date: 2025-02-17 16:46:09.398237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682e6b0f0f9e'
down_revision: Union[str, None] = '6b2d7be8deb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
