"""test running migrations

Revision ID: 764b3f01c6a0
Revises: e5ce81a1538b
Create Date: 2025-02-18 11:16:42.563122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764b3f01c6a0'
down_revision: Union[str, None] = 'e5ce81a1538b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
