"""test running migrations

Revision ID: 8d7e78dfb9d5
Revises: fbb6504c34a8
Create Date: 2025-02-17 19:43:48.955942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7e78dfb9d5'
down_revision: Union[str, None] = 'fbb6504c34a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
