"""test running migrations

Revision ID: 96178a3ad3f1
Revises: da3d55fe7b54
Create Date: 2025-02-16 18:29:57.347175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96178a3ad3f1'
down_revision: Union[str, None] = 'da3d55fe7b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
