"""Income and expense types

Revision ID: b1bbada6924b
Revises: aa6af03b661d
Create Date: 2025-02-07 15:01:16.294665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bbada6924b'
down_revision: Union[str, None] = 'aa6af03b661d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE expensetype ADD VALUE 'office_item';")
    op.execute("ALTER TYPE expensetype ADD VALUE 'tax';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
