"""test running migrations

Revision ID: cce9f9fdf2ed
Revises: b607b5bbd428
Create Date: 2025-02-17 16:25:32.710713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce9f9fdf2ed'
down_revision: Union[str, None] = 'b607b5bbd428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
