"""adding lasting models login and password

Revision ID: d411fbb230d9
Revises: 2af9a43b7aed
Create Date: 2025-02-07 14:03:58.052958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd411fbb230d9'
down_revision: Union[str, None] = '2af9a43b7aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'description')
    # ### end Alembic commands ###
