"""Creatng type for them types

Revision ID: f54f61b05643
Revises: b1bbada6924b
Create Date: 2025-02-07 15:03:33.205654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54f61b05643'
down_revision: Union[str, None] = 'b1bbada6924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE incometype ADD VALUE 'investor';")
    op.execute("ALTER TYPE statustask ADD VALUE 'code_review';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
