"""adding lasting models login and password

Revision ID: fd3b24c205b8
Revises: 8a4ff2f1f125
Create Date: 2025-02-04 17:33:30.001059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3b24c205b8'
down_revision: Union[str, None] = '8a4ff2f1f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_pass_note', sa.Column('name', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_pass_note', 'name')
    # ### end Alembic commands ###
